# -*- coding: utf-8 -*-
"""Group_07_OJO_OLUWAFEMI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzR8uCW58uXAfow5SXHtLJ_dQda52cTh
"""

import time

start_time = time.time()

"""| Field                             | Details                                                    |
| --------------------------------- | ---------------------------------------------------------- |
| **Group number**                  | 07                                                         |
| **Your full name**                | OJO OLUWAFEMI AYOOLA                                                  |
| **Dataset**                       | Heart Failure Prediction                                   |
| **Depth track**                   | Imbalance Depth                                       |
| **Team members**                  | UWAOMA EBUBE KAMALU, AGADAIGHO EXCEL UGOFURE,                                 |
| **Final model**                   | Logistic Regression, `class_weight="Balanced"`, threshold `0.5` |
| **Stratified dummy F1 / ROC AUC** | 0.57 / 0.49                                                |
| **Final model F1 / ROC AUC**      | 0.78 / 0.83                                               |
| **Leakage columns dropped**       | None found                                                 |
| **Full run time on Colab**        | 0.81 minutes                                                  |

**PART 1: DATA FOUNDATION**
"""



import kagglehub

# Download latest version of the data inside the notebook
path = kagglehub.dataset_download("fedesoriano/heart-failure-prediction")

print("Path to dataset files:", path)

import os
import glob
import pandas as pd

csv_files = glob.glob(os.path.join(path, "*.csv"))

print ("CSV files found:")
for file in csv_files:
    print(file)

df = pd.read_csv(csv_files[0])

print("Dataset shape:", df.shape)
df.head(100)

# Connect to SQLite
import sqlite3
conn = sqlite3.connect("my_database.db")

#  Push DataFrame into SQLite Database
df.to_sql(
    "data",
    conn,
    if_exists="replace",
    index=False
)

# 2. Running at least three SQL queries to reveal something useful

query1 = """SELECT * FROM data LIMIT 20;"""
result1 = pd.read_sql_query(query1, conn)
result1

"""### What i Learned

This query allowed me to view the first 20 records in the dataset. I learned about the structure of the data, including the available columns and the type of information stored in each row. It also helped me confirm that the dataset was successfully loaded into the SQLite database and that the records can be retrieved using SQL.
"""

query2 = """
SELECT COUNT(*) AS total_records
FROM data;
"""

result2 = pd.read_sql_query(query2, conn)
result2

"""### What i Learned

The query shows the total number of records in the dataset. This gives an overview of the size of the dataset and helps confirm that all the expected records were successfully loaded into the SQLite database.
"""

query3 = """
SELECT ChestPainType, COUNT(*) AS total
FROM data
GROUP BY ChestPainType
ORDER BY total DESC
LIMIT 10;
"""

result3 = pd.read_sql_query(query3, conn)
result3

"""### What I learned

The results show that ASY (asymptomatic) is the most common chest pain type in the dataset, with 496 patients. NAP (non-anginal pain) is the second most common, followed by ATA (atypical angina). TA (typical angina) is the least common category. This shows that the patients in this dataset are more frequently recorded as asymptomatic than having typical angina.
"""

# Check the number of rows and columns. that is the shape of the dataset
print("Dataset Shape:", df.shape)
print("Rows:", df.shape[0])
print("Column:", df.shape[1])

# Check the data types of each column
df.info()

# Check for missing values
missing_values = df.isnull().sum()
missing_values

# showing the number of patients with and without heart disease
import matplotlib.pyplot as plt

df["HeartDisease"].value_counts().plot(kind="bar")

plt.title("Distribution of Heart Disease")
plt.xlabel("Heart Disease")
plt.ylabel("Number of Patients")
plt.show()

# The Age Range of The Patients
df["Age"].hist()

plt.title("Distribution of Age")
plt.xlabel("Age")
plt.ylabel("Number of Patients")
plt.show()

# Showing The Distribution of Blood Pressure
df["RestingBP"].hist()

plt.title("Distribution of Resting Blood Pressure")
plt.xlabel("Resting Blood Pressure")
plt.ylabel("Number of Patients")
plt.show()

# Showing The Distribution of Cholesterol Measurements
df["Cholesterol"].hist()

plt.title("Distribution of Cholesterol")
plt.xlabel("Cholesterol")
plt.ylabel("Number of Patients")
plt.show()

# Shows The Range of Maximum Heart Rates Recorded
df["MaxHR"].hist()

plt.title("Distribution of Maximum Heart Rate")
plt.xlabel("Maximum Heart Rate")
plt.ylabel("Number of Patients")
plt.show()

# Showing The Distribution of ST Depression Values
df["Oldpeak"].hist()

plt.title("Distribution of Oldpeak")
plt.xlabel("Oldpeak")
plt.ylabel("Number of Patients")
plt.show()

# Creating a copy of the original dataset so that the original data remains unchanged
df_clean = df.copy()

# Checking for Duplicate Rows
print("Duplicate rows:", df_clean.duplicated().sum())

"""I checked for duplicate rows because duplicate patient records could cause some observations to be counted more than once and could bias the analysis or machine-learning model.

Only exact duplicate rows are removed. I do not remove similar-looking patients because two different patients can legitimately have the same health measurements.

Hence no duplicate rows were found, so no records were removed at this stage. Keeping all unique observations ensures that potentially useful patient information is retained.
"""

# Checking for Missing Value
missing = df_clean.isnull().sum()
missing

"""I checked each column for missing values and found no missing values. Therefore, no rows or values were removed or filled."""

#Examining Numerical Variables For Unusual Values
numeric_columns = [
    "Age",
    "RestingBP",
    "Cholesterol",
    "MaxHR",
    "Oldpeak",
    "HeartDisease"
]

df_clean[numeric_columns].describe()

"""I examined the numerical variables for unusual or potentially invalid values. I did not automatically remove outliers because an unusual medical measurement is not necessarily an error. Removing observations without evidence that they are incorrect could eliminate genuine patient information.

"""

# Checking for Suspicious Zero Value
for col in numeric_columns:
    print(f"\n{col}")
    print("Number of zeros:", (df_clean[col] == 0).sum())

"""*Oldpeak* and *HeartDisease* is perfectly valid; it means no ST depression was recorded.
FastingBS is technically represented as a number (0 or 1), but it is actually a binary/categorical variable in this dataset
"""

# Identifying the Row with a Zero Value in RestingBP
df_clean[df_clean["RestingBP"] == 0]

# Identifying the Row with a Zero Value in Cholesterol
df_clean[df_clean["Cholesterol"] == 0]

"""since there are zero values in those columns, I recommend treating them as invalid/missing measurements, rather than assuming that they are genuine measurements."""

# Replacing those specific zero values with NaN.
import numpy as np

df_clean["RestingBP"] = df_clean["RestingBP"].replace(0, np.nan)
df_clean["Cholesterol"] = df_clean["Cholesterol"].replace(0, np.nan)

# To check how many i created
df_clean[["RestingBP", "Cholesterol"]].isnull().sum()

"""I checked zero values separately rather than treating every zero as missing. A value of zero is valid for variables such as FastingBS and Oldpeak, but a zero RestingBP or Cholesterol measurement is not physiologically plausible and is therefore treated as an invalid/missing measurement.

I did not drop these patient records because the other information in the records may still be useful. Instead, these specific invalid values were converted to missing values so that they can be handled appropriately.
"""



#Using The Median for the affected columns
import numpy as np

df_clean["RestingBP"] = df_clean["RestingBP"].replace(0, np.nan)
df_clean["Cholesterol"] = df_clean["Cholesterol"].replace(0, np.nan)

df_clean["RestingBP"] = df_clean["RestingBP"].fillna(
    df_clean["RestingBP"].median()
)

df_clean["Cholesterol"] = df_clean["Cholesterol"].fillna(
    df_clean["Cholesterol"].median()
)

''' PRINTING OUT THE ORIGINAL SHAPE,CLEANED SHAPE,
 MISSING VALUE AND DUPLICATE ROWS AND ALSO
 CHECKING IF THOSE ROWS WITH INVALID ZERO VALUE HAVE BEEN REPLACED WITH MEDIAN'''

print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicates:", df_clean.duplicated().sum())

# Identifying if the Row with a Zero Value in RestingBP still remain
df_clean[df_clean["RestingBP"] == 0]

# Identifying if the Row with a Zero Value in Cholesterol still remain
df_clean[df_clean["Cholesterol"] == 0]

"""I checked zero values individually rather than treating all zeros as missing. Zero is a valid value for variables such as FastingBS and Oldpeak. However, a zero value for RestingBP or Cholesterol is not a plausible physiological measurement, so these values were treated as invalid/missing.

I replaced only these specific invalid values with the median of their respective columns. The median was chosen because it is less affected by extreme values than the mean. I did not drop the entire patient records because their other information may still be useful.

### Final Cleaning Summary

The dataset was cleaned by checking for missing values, duplicate records, invalid measurements, and categorical values. No rows were unnecessarily dropped. Valid zero values were retained, while potentially invalid zero measurements in RestingBP and Cholesterol were handled separately. This approach avoids blanket data-filling methods and preserves as much valid patient information as possible.
"""

df_clean

"""**PART 2: FEATURE ENGINEERING AND ENCODING**"""

# Feature 1 - Age Group
# creating AgeGroup by converting the continuous Age variable into ranges

df_clean["AgeGroup"] = pd.cut(
    df_clean["Age"],
    bins=[0, 40, 50, 60, 100],
    labels=["Under 40", "40-49", "50-59", "60+"]
)

df_clean[["Age", "AgeGroup"]].head()

"""### Feature 1: Age Group
The business reasoning is that grouping patients into age segments makes it easier to identify and communicate patterns between different age groups. This also provides a simpler categorical feature that a machine-learning model can use alongside the original Age variable.
"""

# Maximum Heart Rate per Age
'''creating a ratio that combines two existing variables
 and provides a relative measure of maximum heart rate based on age'''

df_clean["MaxHR_per_Age"] = df_clean["MaxHR"] / df_clean["Age"]

df_clean[["Age", "MaxHR", "MaxHR_per_Age"]].head()

"""### Feature 2: Maximum Heart Rate per Age

I created MaxHR_per_Age by dividing MaxHR by Age. This creates a ratio that combines two existing variables and provides a relative measure of maximum heart rate based on age. The business reasoning is that relationships between variables may reveal patterns that are not as obvious when each variable is considered separately.
"""

# comparing Oldpeak values relative to a patient's age
df_clean["Oldpeak_Per_Age"] = df_clean["Oldpeak"] / df_clean["Age"]

df_clean[["Age", "Oldpeak", "Oldpeak_Per_Age"]].head()

"""### Feature 3: Oldpeak per Age
The Business reasoning is that it provide an additional variable for exploring relationships in the data and determining whether age-related differences in Oldpeak are associated with the target variable, HeartDisease
"""

# CHECKING ALL THE THREE NEW FEATURES
df_clean[[
    "Age",
    "AgeGroup",
    "MaxHR",
    "MaxHR_per_Age",
    "Oldpeak",
    "Oldpeak_Per_Age"
]].head(10)

# Label encoding for binary categorical columns
df_clean["Sex"] = df_clean["Sex"].map({"M": 1, "F": 0})
df_clean["ExerciseAngina"] = df_clean["ExerciseAngina"].map({"Y": 1, "N": 0})

# One-hot encoding for categorical columns with more than two categories
df_clean = pd.get_dummies(
    df_clean,
    columns=["ChestPainType", "RestingECG", "ST_Slope"],
    drop_first=True,
    dtype=int
)

# Encode target variable
df_clean["HeartDisease"] = df_clean["HeartDisease"].astype(int)

df_clean.head(10)

df_clean2 = df_clean.copy()
df_clean2.head(10)

"""**Categorical Encoding**

I encoded every categorical variable so that the dataset can be used effectively for analysis and machine learning models.

1. **Sex: Label Encoding**

Sex contains only two categories: Male (M) and Female (F). I used label encoding, assigning M = 1 and F = 0. Since there are only two categories, this provides a simple binary representation without creating unnecessary columns.

2. **ExerciseAngina: Label Encoding**

ExerciseAngina also has only two categories: Yes (Y) and No (N). I encoded Y = 1 and N = 0 because it is a binary variable and label encoding is appropriate.

3. **ChestPainType: One-Hot Encoding**

ChestPainType has multiple categories, so I used one-hot encoding rather than assigning numerical values. This prevents the encoded values from implying an artificial ranking between the different chest pain categories.

4. **RestingECG: One-Hot Encoding**

RestingECG contains multiple categories, so one-hot encoding was used. Each category is represented by a separate binary column without creating an artificial order.

5. **ST_Slope: One-Hot Encoding**

ST_Slope has multiple categorical values, so I used one-hot encoding. This allows each category to be represented independently.

Why drop_first=True?

I used drop_first=True for the multi-category variables to remove one dummy column from each categorical variable. The remaining columns still contain enough information to determine the original category, while avoiding redundant dummy variables and reducing the risk of multicollinearity in models that are sensitive to it.

Target variable: HeartDisease

HeartDisease is already binary, with 0 and 1 representing the two target classes, so no additional one-hot encoding is necessary.
"""

from sklearn.preprocessing import StandardScaler
numeric_target = ["HeartDisease"]
numeric_features = [
    "Age",
    "RestingBP",
    "Cholesterol",
    "MaxHR",
    "Oldpeak"
]

scaler = StandardScaler()

df_clean2[numeric_features] = scaler.fit_transform(
    df_clean2[numeric_features]
)

df_clean2[numeric_features]
Scaled= df_clean2[numeric_features]
Scaled

target = df_clean2[numeric_target]
target

"""**Feature Scaling**

I chose StandardScaler to scale the numerical features in the dataset.

StandardScaler transforms the features so that they have a mean of approximately 0 and a standard deviation of 1. This is useful because the dataset contains features measured on very different scales. For example, Age, RestingBP, Cholesterol, MaxHR, and Oldpeak have different ranges and units.

Standardizing the features prevents variables with larger numerical values from having an unnecessarily greater influence on models that are sensitive to feature scale.

I chose StandardScaler instead of MinMaxScaler because StandardScaler is generally suitable when the numerical features have different ranges and may contain extreme observations. The dataset contains some relatively high Cholesterol and other numerical values, so StandardScaler is a reasonable choice for bringing the features onto a comparable scale.

The HeartDisease target variable is excluded from scaling because it is the target, not an input feature.

Since i used one-hot encoding, i do not need to standardize those binary 0/1 columns. A cleaner approach is to scale only the continuous numerical features

**PART 3 : CLUSTERING ANALYSIS**
"""

# Importing KMeans and silhouette_score
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

inertia = []
silhouette_scores = []

K_range = range(2, 11)

for k in K_range:
    # Initialize K-Means
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    # Fit the model and predict clusters
    labels = kmeans.fit_predict(Scaled)

    # Record inertia
    inertia.append(kmeans.inertia_)

    # Calculate silhouette score
    score = silhouette_score(Scaled, labels)
    silhouette_scores.append(score)

    print(f"K = {k}, "
          f"Inertia = {kmeans.inertia_:.2f}, "
          f"Silhouette Score = {score:.4f}")

# Create a figure with two plots
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ---------------------------
# Elbow Curve
# ---------------------------
axes[0].plot(
    list(K_range),
    inertia,
    marker='o'
)

axes[0].set_title('Elbow Curve for K-Means')
axes[0].set_xlabel('Number of Clusters (K)')
axes[0].set_ylabel('Inertia')
axes[0].set_xticks(list(K_range))
axes[0].grid(True)

# Silhouette Scores
axes[1].plot(
    list(K_range),
    silhouette_scores,
    marker='o'
)

axes[1].set_title('Silhouette Scores for K-Means')
axes[1].set_xlabel('Number of Clusters (K)')
axes[1].set_ylabel('Silhouette Score')
axes[1].set_xticks(list(K_range))
axes[1].grid(True)

plt.tight_layout()
plt.show()



"""The K-Means algorithm was evaluated for values of K ranging from 2 to 10 using both the elbow method and silhouette scores. The inertia decreased as the number of clusters increased, from 3535.35 at K = 2 to 1922.00 at K = 10. However, the reduction in inertia becomes progressively smaller as K increases, indicating diminishing returns from adding more clusters.

The silhouette scores provide a second signal for selecting K. The highest silhouette score was obtained at K = 2, with a score of 0.2175. The score decreased substantially at K = 3 (0.1779) and remained relatively low for the other values of K, with the highest subsequent value being 0.1866 at K = 5.

Based on both measures, K = 2 was selected as the final number of clusters. Although the silhouette score is relatively low, K=2 is the best of the tested choices, but the dataset does not exhibit particularly strong natural clustering., while the inertia curve indicates that increasing K provides diminishing improvements in within-cluster compactness.
"""

# Add cluster labels to a copy of the data
Scaled_clean = Scaled.copy()
Scaled_clean["Cluster"] = labels
print(Scaled_clean["Cluster"].value_counts().sort_index())

# Calculate the mean of each feature by cluster
cluster_means = Scaled_clean.groupby('Cluster')[numeric_features].mean()

# Round the results for easier reading
cluster_means = cluster_means.round(3)

display(cluster_means)



from sklearn.decomposition import PCA

#Apply PCA and reduce to 2 dimensions
pca = PCA(n_components=2)
pca = pca.fit_transform(Scaled)

# Create a dataframe containing the two principal components
pca_df = pd.DataFrame(
    pca,
    columns=["PC1", "PC2"],
    index=df_clean.index
)

# Add the cluster labels
pca_df["Cluster"] = Scaled_clean["Cluster"].values

# Plot the clusters
plt.figure(figsize=(8, 6))

for cluster in sorted(pca_df["Cluster"].unique()):
    cluster_data = pca_df[pca_df["Cluster"] == cluster]
    plt.scatter(
        cluster_data["PC1"],
        cluster_data["PC2"],
        label=f"Cluster {cluster}"
    )

plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("Clusters Visualized Using PCA")
plt.legend()
plt.show()

"""**PART 4: CLASSIFICATION**"""

X_scaled  = Scaled
y = df["HeartDisease"]
# Unscaled
X_unscaled = df[['Age', 'RestingBP', 'Cholesterol','MaxHR', 'Oldpeak']]
y = df["HeartDisease"]

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# --------------------------------------------------
# 1. Define X and y
# --------------------------------------------------

X_unscaled = df[
    ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']
]

y = df["HeartDisease"]


# --------------------------------------------------
# 2. Split the UNSCALED data
# --------------------------------------------------

X_unscaled_train, X_unscaled_test, y_train, y_test = train_test_split(
    X_unscaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# --------------------------------------------------
# 3. Create the scaler
# --------------------------------------------------

scaler = StandardScaler()


# --------------------------------------------------
# 4. Fit scaler ONLY on training data
# --------------------------------------------------

X_train_scaled = scaler.fit_transform(X_unscaled_train)


# --------------------------------------------------
# 5. Transform test data using the SAME scaler
# --------------------------------------------------

X_test_scaled = scaler.transform(X_unscaled_test)


# --------------------------------------------------
# 6. Convert back to DataFrames
# --------------------------------------------------

X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_unscaled.columns,
    index=X_unscaled_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_unscaled.columns,
    index=X_unscaled_test.index
)


# Check
print("X_train_scaled:", X_train_scaled.shape)
print("X_test_scaled:", X_test_scaled.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

"""I will be training the following classifiers
1. Logistic Regression
2. KNeighborsClassifier
3. Decision Tree Classifier


"""

from sklearn.model_selection import StratifiedKFold, cross_validate, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
# Classification models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay
)

# Stratified 5-Fold Cross-Validation

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Define models

models = {

    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(random_state=42))
    ]),

    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier())
    ]),

    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    )
}

# Metrics

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

#  Cross-validation results

results = []

for name, model in models.items():

    scores = cross_validate(
        model,
        X_unscaled,
        y,
        cv=skf,
        scoring=scoring,
        return_train_score=False
    )

    results.append({
        "Model": name,

        "Accuracy Mean": scores["test_accuracy"].mean(),
        "Accuracy SD": scores["test_accuracy"].std(),

        "Precision Mean": scores["test_precision"].mean(),
        "Precision SD": scores["test_precision"].std(),

        "Recall Mean": scores["test_recall"].mean(),
        "Recall SD": scores["test_recall"].std(),

        "F1 Mean": scores["test_f1"].mean(),
        "F1 SD": scores["test_f1"].std(),

        "ROC AUC Mean": scores["test_roc_auc"].mean(),
        "ROC AUC SD": scores["test_roc_auc"].std()
    })


# --------------------------------------------------
# 6. Comparison table
# --------------------------------------------------

comparison = pd.DataFrame(results)

print(comparison.round(2))

report = pd.DataFrame({
    "Model": comparison["Model"],

    "Accuracy": (
        comparison["Accuracy Mean"].round(2).astype(str)
        + " ± "
        + comparison["Accuracy SD"].round(2).astype(str)
    ),

    "Precision": (
        comparison["Precision Mean"].round(2).astype(str)
        + " ± "
        + comparison["Precision SD"].round(2).astype(str)
    ),

    "Recall": (
        comparison["Recall Mean"].round(2).astype(str)
        + " ± "
        + comparison["Recall SD"].round(2).astype(str)
    ),

    "F1": (
        comparison["F1 Mean"].round(2).astype(str)
        + " ± "
        + comparison["F1 SD"].round(2).astype(str)
    ),

    "ROC AUC": (
        comparison["ROC AUC Mean"].round(2).astype(str)
        + " ± "
        + comparison["ROC AUC SD"].round(2).astype(str)
    )
})

report = report.set_index("Model")

report

"""Logistic Regression: Provides a simple baseline for classification and works well with scaled features.

KNN: Uses distances between observations, making it useful for evaluating the effect of feature scaling.

Decision Tree: Can model nonlinear relationships and generally does not require feature scaling.
"""

for name, model in models.items():

    # Generate out-of-fold predictions
    y_pred = cross_val_predict(
        model,
        X_unscaled,
        y,
        cv=skf,
        method="predict"
    )

    # Confusion matrix
    cm = confusion_matrix(y, y_pred)

    print(f"\n{name}")
    print(cm)

    # Plot
    ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=["No Disease", "Disease"]
    ).plot()

    plt.title(f"Confusion Matrix - {name}")
    plt.show()

"""**PART 5 : IMBALANCE HANDLING**"""

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.metrics import precision_recall_curve, confusion_matrix

# Models with SMOTE
models = {
    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("model", KNeighborsClassifier())
    ]),

    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("model", LogisticRegression(random_state=42))
    ]),

    "Decision Tree": Pipeline([
        ("smote", SMOTE(random_state=42)),
        ("model", DecisionTreeClassifier(random_state=42))
    ])
}

print("Original class distribution:")
print(y.value_counts())

# Business costs
C_FN = 5
C_FP = 1

# Inner CV for obtaining out-of-fold probabilities
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

threshold_results = {}

for name, model in models.items():

    # Get out-of-fold probabilities
    y_prob = cross_val_predict(
        model,
        X_unscaled,
        y,
        cv=cv,
        method="predict_proba"
    )[:, 1]

    # Precision-recall curve
    precision, recall, thresholds = precision_recall_curve(
        y,
        y_prob
    )

    # Find threshold with minimum business cost
    costs = []

    for threshold in thresholds:

        y_pred = (y_prob >= threshold).astype(int)

        tn, fp, fn, tp = confusion_matrix(
            y,
            y_pred,
            labels=[0, 1]
        ).ravel()

        total_cost = (
            C_FP * fp +
            C_FN * fn
        )

        costs.append(total_cost)

    # Select threshold with lowest cost
    best_index = np.argmin(costs)
    best_threshold = thresholds[best_index]

    threshold_results[name] = best_threshold

    print(f"{name}")
    print(f"Best threshold: {best_threshold:.3f}")
    print(f"Minimum business cost: {costs[best_index]}")
    print()

plt.figure(figsize=(8, 6))

for name, model in models.items():

    y_prob = cross_val_predict(
        model,
        X_unscaled,
        y,
        cv=cv,
        method="predict_proba"
    )[:, 1]

    precision, recall, thresholds = precision_recall_curve(
        y,
        y_prob
    )

    threshold = threshold_results[name]

    # Find closest threshold on the PR curve
    idx = np.argmin(
        np.abs(thresholds - threshold)
    )

    plt.plot(
        recall,
        precision,
        label=name
    )

    plt.scatter(
        recall[idx],
        precision[idx],
        s=80
    )

    plt.annotate(
        f"Threshold = {threshold:.3f}",
        (recall[idx], precision[idx])
    )

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curves with Cost-Based Thresholds")
plt.legend()
plt.grid(True)
plt.show()

for name, threshold in threshold_results.items():
    print(f"{name}: threshold = {threshold:.3f}")

y_pred = (y_prob >= threshold).astype(int)

"""Threshold tuning was performed using precision-recall curves. A false negative was assigned a cost of 5, while a false positive was assigned a cost of 1, reflecting the assumption that failing to identify a patient with heart disease is more costly than incorrectly flagging a patient for further evaluation. The threshold minimizing the total business cost was selected for each model."""

# Class distribution
class_counts = y.value_counts()
class_percent = y.value_counts(normalize=True) * 100

print("Class counts:")
print(class_counts)

print("\nClass percentages:")
print(class_percent)

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline as SklearnPipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE


# ---------------------------------------------------------
# Models
# ---------------------------------------------------------

class_weight_models = {
    "KNN": SklearnPipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier())
    ])
        ,

    "Logistic Regression": SklearnPipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            class_weight="balance",
            random_state=42,
            max_iter=1000

            ))
    ]),

    "Decision Tree": DecisionTreeClassifier(
        class_weight="balanced",
        random_state=42
        )
}


baseline_models = {
    "KNN": SklearnPipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier())
    ]),

    "Logistic Regression": SklearnPipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(random_state=42))
    ]),

    "Decision Tree": DecisionTreeClassifier(random_state=42)
}


smote_models = {
    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("model", KNeighborsClassifier())
    ]),

    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("model", LogisticRegression(random_state=42))
    ]),

    "Decision Tree": Pipeline([
        ("smote", SMOTE(random_state=42)),
        ("model", DecisionTreeClassifier(random_state=42))
    ])
}


# ---------------------------------------------------------
# 5-fold stratified CV
# ---------------------------------------------------------

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# ---------------------------------------------------------
# Evaluation function
# ---------------------------------------------------------

def evaluate_model(model, X_unscaled, y, threshold=0.50):

    accuracy = []
    precision = []
    recall = []
    f1 = []
    auc = []

    for train_idx, test_idx in cv.split(X_unscaled, y):

        X_train = X_unscaled.iloc[train_idx]
        X_test = X_unscaled.iloc[test_idx]

        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]

        model.fit(X_train, y_train)

        y_prob = model.predict_proba(X_test)[:, 1]

        y_pred = (y_prob >= threshold).astype(int)

        accuracy.append(
            accuracy_score(y_test, y_pred)
        )

        precision.append(
            precision_score(
                y_test,
                y_pred,
                zero_division=0
            )
        )

        recall.append(
            recall_score(
                y_test,
                y_pred,
                zero_division=0
            )
        )

        f1.append(
            f1_score(
                y_test,
                y_pred,
                zero_division=0
            )
        )

        auc.append(
            roc_auc_score(y_test, y_prob)
        )

    return {
        "Accuracy": np.mean(accuracy),
        "Precision": np.mean(precision),
        "Recall": np.mean(recall),
        "F1": np.mean(f1),
        "ROC AUC": np.mean(auc)
    }


# ---------------------------------------------------------
# Compare baseline and SMOTE
# ---------------------------------------------------------

comparison = []

for name in baseline_models:

    # Baseline
    baseline_scores = evaluate_model(
        baseline_models[name],
        X_unscaled,
        y,
        threshold=0.50
    )

    comparison.append({
        "Model": name,
        "Technique": "Baseline",
        **baseline_scores
    })

    # SMOTE
    smote_scores = evaluate_model(
        smote_models[name],
        X_unscaled,
        y,
        threshold=0.50
    )

    comparison.append({
        "Model": name,
        "Technique": "SMOTE",
        **smote_scores
    })


comparison_table = pd.DataFrame(comparison)

comparison_table[
    ["Accuracy", "Precision", "Recall", "F1", "ROC AUC"]
] = comparison_table[
    ["Accuracy", "Precision", "Recall", "F1", "ROC AUC"]
].round(2)

comparison_table

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    precision_recall_curve,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
import numpy as np


# Business cost
C_FN = 5
C_FP = 1

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# ---------------------------------------------------------
# Find cost-sensitive threshold
# ---------------------------------------------------------

def find_best_threshold(y_true, y_prob):

    precision, recall, thresholds = precision_recall_curve(
        y_true,
        y_prob
    )

    best_threshold = 0.5
    lowest_cost = np.inf

    for threshold in thresholds:

        y_pred = (y_prob >= threshold).astype(int)

        tn, fp, fn, tp = confusion_matrix(
            y_true,
            y_pred,
            labels=[0, 1]
        ).ravel()

        cost = C_FP * fp + C_FN * fn

        if cost < lowest_cost:
            lowest_cost = cost
            best_threshold = threshold

    return best_threshold


# ---------------------------------------------------------
# Evaluate SMOTE + threshold tuning
# ---------------------------------------------------------

threshold_results_table = []

for name, model in smote_models.items():

    fold_accuracy = []
    fold_precision = []
    fold_recall = []
    fold_f1 = []
    fold_auc = []

    for train_idx, test_idx in cv.split(X_unscaled, y):

        X_train = X_unscaled.iloc[train_idx]
        X_test = X_unscaled.iloc[test_idx]

        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]

        # Fit SMOTE model on training fold
        model.fit(X_train, y_train)

        # Probabilities
        train_prob = model.predict_proba(X_train)[:, 1]
        test_prob = model.predict_proba(X_test)[:, 1]

        # Tune threshold using training data
        threshold = find_best_threshold(
            y_train,
            train_prob
        )

        # Apply selected threshold to test fold
        y_pred = (
            test_prob >= threshold
        ).astype(int)

        fold_accuracy.append(
            accuracy_score(y_test, y_pred)
        )

        fold_precision.append(
            precision_score(
                y_test,
                y_pred,
                zero_division=0
            )
        )

        fold_recall.append(
            recall_score(
                y_test,
                y_pred,
                zero_division=0
            )
        )

        fold_f1.append(
            f1_score(
                y_test,
                y_pred,
                zero_division=0
            )
        )

        # ROC AUC uses probabilities, not thresholded predictions
        fold_auc.append(
            roc_auc_score(y_test, test_prob)
        )

    threshold_results_table.append({
        "Model": name,
        "Technique": "SMOTE + Threshold",
        "Accuracy": np.mean(fold_accuracy),
        "Precision": np.mean(fold_precision),
        "Recall": np.mean(fold_recall),
        "F1": np.mean(fold_f1),
        "ROC AUC": np.mean(fold_auc)
    })


threshold_table = pd.DataFrame(
    threshold_results_table
)

threshold_table[
    ["Accuracy", "Precision", "Recall", "F1", "ROC AUC"]
] = threshold_table[
    ["Accuracy", "Precision", "Recall", "F1", "ROC AUC"]
].round(2)

threshold_table

"""Logistic Regression + SMOTE + cost-sensitive thresholding is the selected configuration because the stated cost prioritizes avoiding false negatives."""

from sklearn.dummy import DummyClassifier
# Create stratified dummy classifier
dummy = DummyClassifier(strategy="stratified", random_state=42)

# Fit on training data
dummy.fit(X_train, y_train)

# Predictions and probabilities
y_dummy_pred = dummy.predict(X_test)
y_dummy_prob = dummy.predict_proba(X_test)[:, 1]

# Create DataFrame
dummy_results = pd.DataFrame({
    "Model": ["Stratified Dummy"],
    "Accuracy": [accuracy_score(y_test, y_dummy_pred)],
    "Precision": [precision_score(y_test, y_dummy_pred, zero_division=0)],
    "Recall": [recall_score(y_test, y_dummy_pred, zero_division=0)],
    "F1": [f1_score(y_test, y_dummy_pred, zero_division=0)],
    "ROC AUC": [roc_auc_score(y_test, y_dummy_prob)]
})

# Round results
dummy_results = dummy_results.round(2)

dummy_results

"""**PART 6 : THE TIE IN**"""

#Combine clusters with target


cluster_results = pd.DataFrame({
    "Cluster": labels,
    "HeartDisease": target["HeartDisease"]
})


cluster_target_summary = cluster_results.groupby("Cluster").agg(
    Cluster_Size=("HeartDisease", "size"),
    Positive_Cases=("HeartDisease", "sum"),
    Positive_Class_Rate=("HeartDisease", "mean")
)

# Convert rate from proportion to percentage
cluster_target_summary["Positive_Class_Rate"] *= 100

cluster_target_summary = cluster_target_summary.round(2)

display(cluster_target_summary)

"""The results show that some clusters have a much higher positive-class rate than others, which suggests that the clustering has captured meaningful structure related to the HeartDisease label

**The strongest clusters are:**

Cluster 7: 91.80% positive
            


Cluster 3: 88.52% positive
            


Cluster 2: 80.00% positive
            


Cluster 1: 70.71% positive

Several clusters showed strong differences in their positive-class rates, suggesting that the clustering captured meaningful structure related to the HeartDisease label. Clusters 7 and 3 had the highest positive-class rates at 91.80% and 88.52%, respectively, followed by Cluster 2 at 80.00% and Cluster 1 at 70.71%. In contrast, Cluster 6 had a positive-class rate of only 23.81%, while Clusters 0 and 9 had rates of 28.83%. Since K-Means was performed without using the target variable, these differences suggest that the underlying patient characteristics used for clustering contain information associated with heart disease status. However, the clusters should be interpreted as patient subgroups rather than direct predictors, because K-Means is an unsupervised method

**PART 7 : CONCLUSION AND RECOMMENDATION**

**DEPTH TRACK** : IMBALANCE WAS WORKED ON
"""

# ============================================================
# BASELINE vs CLASS WEIGHTING vs SMOTE
# 5-FOLD STRATIFIED CROSS-VALIDATION
# ============================================================

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE


# ------------------------------------------------------------
# 1. STRATIFIED 5-FOLD CV
# ------------------------------------------------------------

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# ------------------------------------------------------------
# 2. SCORING METRICS
# ------------------------------------------------------------

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}


# ------------------------------------------------------------
# 3. DEFINE MODELS
# ------------------------------------------------------------

models = {

    # ========================================================
    # LOGISTIC REGRESSION
    # ========================================================

    "Logistic Regression - Baseline": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            random_state=42,
            max_iter=1000
        ))
    ]),

    "Logistic Regression - Class Weight": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            class_weight="balanced",
            random_state=42,
            max_iter=1000
        ))
    ]),

    "Logistic Regression - SMOTE": ImbPipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("model", LogisticRegression(
            random_state=42,
            max_iter=1000
        ))
    ]),


    # ========================================================
    # KNN
    # ========================================================

    "KNN - Baseline": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier())
    ]),

    # KNN does NOT support class_weight.
    # Therefore there is no KNN - Class Weight model.

    "KNN - SMOTE": ImbPipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("model", KNeighborsClassifier())
    ]),


    # ========================================================
    # DECISION TREE
    # ========================================================

    "Decision Tree - Baseline": DecisionTreeClassifier(
        random_state=42
    ),

    "Decision Tree - Class Weight": DecisionTreeClassifier(
        class_weight="balanced",
        random_state=42
    ),

    "Decision Tree - SMOTE": ImbPipeline([
        ("smote", SMOTE(random_state=42)),
        ("model", DecisionTreeClassifier(
            random_state=42
        ))
    ])
}


# ------------------------------------------------------------
# 4. RUN 5-FOLD CROSS-VALIDATION
# ------------------------------------------------------------

results = []

for name, model in models.items():

    scores = cross_validate(
        model,
        X_unscaled,
        y,
        cv=skf,
        scoring=scoring,
        return_train_score=False,
        n_jobs=-1
    )

    results.append({
        "Model": name,

        "Accuracy Mean": scores["test_accuracy"].mean(),
        "Accuracy SD": scores["test_accuracy"].std(),

        "Precision Mean": scores["test_precision"].mean(),
        "Precision SD": scores["test_precision"].std(),

        "Recall Mean": scores["test_recall"].mean(),
        "Recall SD": scores["test_recall"].std(),

        "F1 Mean": scores["test_f1"].mean(),
        "F1 SD": scores["test_f1"].std(),

        "ROC AUC Mean": scores["test_roc_auc"].mean(),
        "ROC AUC SD": scores["test_roc_auc"].std()
    })


# ------------------------------------------------------------
# 5. CREATE COMPARISON TABLE
# ------------------------------------------------------------

comparison = pd.DataFrame(results)

print("BASELINE vs CLASS WEIGHTING vs SMOTE")
display(comparison.round(2))

"""
**PART 7 : CONCLUSION AND RECOMMENDATION**

Based on these results, I would deploy Logistic Regression with class weighting because it achieved the highest precision (0.81), while maintaining strong F1 (0.78) and ROC AUC (0.83), with stable performance across folds. With another month, I would focus on hyperparameter tuning, feature engineering, threshold optimisation, and external validation. The clustering results could reveal hidden customer segments or behavioural patterns that the classifier missed because classification predicts predefined labels, while clustering can uncover previously unknown groups. The hardest decision was choosing between baseline Logistic Regression, class weighting, and SMOTE, since all three achieved similar accuracy and ROC AUC, but class weighting provided the best precision without sacrificing overall F1 performance."""

# ============================================================
# PRECISION-RECALL CURVES
# ============================================================

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import precision_recall_curve, average_precision_score
import matplotlib.pyplot as plt

# Store out-of-fold probabilities
oof_probabilities = {}

for name, model in models.items():

    y_prob = cross_val_predict(
        model,
        X_unscaled,
        y,
        cv=skf,
        method="predict_proba",
        n_jobs=-1
    )[:, 1]

    oof_probabilities[name] = y_prob


# ============================================================
# PLOT PR CURVES
# ============================================================

for model_type in [
    "Logistic Regression",
    "KNN",
    "Decision Tree"
]:

    plt.figure(figsize=(8, 6))

    for name, y_prob in oof_probabilities.items():

        if name.startswith(model_type):

            precision, recall, thresholds = precision_recall_curve(
                y,
                y_prob
            )

            ap = average_precision_score(
                y,
                y_prob
            )

            plt.plot(
                recall,
                precision,
                label=f"{name} (AP = {ap:.3f})"
            )

    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.title(f"Precision-Recall Curve - {model_type}")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.show()

# ============================================================
# FINAL OPERATING POINT: DEFAULT THRESHOLD = 0.5
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

THRESHOLD = 0.5

# Example cost assumptions
COST_FP = 1
COST_FN = 5

final_results = []

for name, y_prob in oof_probabilities.items():

    # Apply default threshold of 0.5
    y_pred = (y_prob >= THRESHOLD).astype(int)

    # Confusion matrix components
    TP = np.sum((y == 1) & (y_pred == 1))
    TN = np.sum((y == 0) & (y_pred == 0))
    FP = np.sum((y == 0) & (y_pred == 1))
    FN = np.sum((y == 1) & (y_pred == 0))

    # Cost
    total_cost = (
        FP * COST_FP +
        FN * COST_FN
    )

    final_results.append({
        "Model": name,
        "Threshold": THRESHOLD,
        "Accuracy": accuracy_score(y, y_pred),
        "Precision": precision_score(
            y, y_pred, zero_division=0
        ),
        "Recall": recall_score(
            y, y_pred, zero_division=0
        ),
        "F1": f1_score(
            y, y_pred, zero_division=0
        ),
        "ROC AUC": roc_auc_score(y, y_prob),
        "TP": TP,
        "TN": TN,
        "FP": FP,
        "FN": FN,
        "Total Cost": total_cost
    })


final_operating_point = pd.DataFrame(final_results)

display(
    final_operating_point.round(2)
)

"""**FINAL OPERATING POINT**
The default classification threshold of 0.5 was used as the final operating point. Predictions with a probability of at least 0.5 were classified as class 1, while probabilities below 0.5 were classified as class 0. The operating point was evaluated using precision, recall, F1-score, ROC-AUC, false positives, false negatives, and the specified misclassification costs. Total cost was calculated as the number of false positives multiplied by the false-positive cost plus the number of false negatives multiplied by the false-negative cost. This provides a transparent assessment of the trade-off between false positives and false negatives at the standard 0.5 threshold.

"""

end_time = time.time()

total_seconds = end_time - start_time
total_minutes = total_seconds / 60

print(f"Total runtime: {total_minutes:.2f} minutes")